FROM node:16-alpine
WORKDIR /usr/local/apps/myapp

COPY src/package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/myapp/dev

COPY src ./src
COPY .env ./

EXPOSE ${PORT}

WORKDIR /usr/local/apps/myapp/dev/src

ENTRYPOINT []