FROM node:16-alpine

WORKDIR /app

COPY package.json ./
COPY .env.dev ./.env

RUN npm install && npm cache clean --force
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /src

COPY src .

EXPOSE ${PORT}

WORKDIR /app

ENTRYPOINT []