version: '3.4'
services:

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=JQODI9u1uioasdjkl][]12039dasjkl!@((Adlakjsdl))
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  cover_crops_api:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile.dev
     args:
       - PORT=${APP_PORT}
   command: sh -c  "npm run db-fresh && npm run db-seed && npm run dev"
   ports:
     - 3000:${APP_PORT}
   env_file:
     - .env
   volumes:
     - ./:/usr/local/apps/app
     - ignore:/usr/local/apps/app/node_modules
  
  example_client_api:
    restart: always
    build:
      context: ./_sandbox/observer-api
      args:
        - PORT=${APP_PORT}
    ports:
      - 3002:${APP_PORT}
    env_file:
      - ./_sandbox/observer-api/.env

volumes:
  db:
    driver: local
  cache:
    driver: local
  ignore: