FROM node:16-alpine

WORKDIR /usr/local/apps/app

COPY package.json ./
COPY .env ./.env

RUN npm install && npm cache clean --force
ENV PATH=/usr/local/apps/app/node_modules/.bin:$PATH

COPY ./src ./src

EXPOSE ${PORT}

ENTRYPOINT []