
@auth_token = {{get_auth_token.response.body.data}}
@post_id = {{get_posts.response.body.data[0].id}}
@comment_id = {{get_comments.response.body.data[0].id}}


###
# @name get_auth_token
GET {{protocol}}://{{auth-domain}}/auth
?key={{key}}
&secret={{secret}}


###
# @name get_posts
GET {{protocol}}://{{domain}}/posts
Authorization: {{auth_token}}


###
# @name create_comment
POST {{protocol}}://{{domain}}/posts/{{post_id}}/comments
Authorization: {{auth_token}}
content-type: application/json

{
    "title":"some title",
    "body":"bodie odie odie"
}


###
# @name get_comments
GET {{protocol}}://{{domain}}/posts/{{post_id}}/comments
Authorization: {{auth_token}}


###
# @name update_comment
PUT {{protocol}}://{{domain}}/posts/{{post_id}}/comments/{{comment_id}}
Authorization: {{auth_token}}
content-type: application/json

{
    "title":"new title",
    "body":"bodie odie odie odie heeenneeyyy"
}


###
# @name retrieve_comment
GET {{protocol}}://{{domain}}/posts/{{post_id}}/comments/{{comment_id}}
Authorization: {{auth_token}}


###
# @name delete_comment
DELETE {{protocol}}://{{domain}}/posts/{{post_id}}/comments/{{comment_id}}
Authorization: {{auth_token}}

