
@auth_token = {{get_auth_token.response.body.data}}
@crop_id = {{create_crops.response.body.data.id}}
###
# @name get_auth_token
GET {{protocol}}://{{auth-domain}}/auth
?key={{key}}
&secret={{secret}}

###
# @name create_crops
POST {{protocol}}://{{domain}}/crops
Authorization: {{auth_token}}
content-type: application/json

{
    "label":"Test Crop",
    "scientificName":"Test",
    "usdaSymbol":"TST"
}

###
# @name get_crops
GET {{protocol}}://{{domain}}/crops
?limit=2
Authorization: {{auth_token}}


###
# @name retrieve_crop
GET {{protocol}}://{{domain}}/crops/{{crop_id}}
Authorization: {{auth_token}}

###
# @name update_crop
PUT {{protocol}}://{{domain}}/crops/{{crop_id}}
Authorization: {{auth_token}}
content-type: application/json

{
    "label":"Test Crop",
    "scientificName":"Test",
    "usdaSymbol":"TST1"
}

###
# @name delete_crop
DELETE {{protocol}}://{{domain}}/crops/{{crop_id}}
Authorization: {{auth_token}}
