
@auth_token = {{get_auth_token.response.body.data}}

###
# @name get_auth_token
GET {{protocol}}://{{auth-domain}}/auth
?key={{key}}
&secret={{secret}}

###
# @name create_groups
POST {{protocol}}://{{domain}}/groups
Authorization: {{auth_token}}
content-type: application/json

{
    "title":"some title",
    "body":"bodie odie odie"
}

###
# @name get_groups
GET {{protocol}}://{{domain}}/groups
Authorization: {{auth_token}}

